#!/usr/bin/env bash
# This script counts IP and HTTP code occurrences in the Apache log
# and sorts them from highest to lowest

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' apache-access.log | sort -nr

