#!/usr/bin/env bash
# This script counts IP and HTTP code occurrences in the Apache log
# Usage: ./14-dig_the-data <apache_log_file>

awk '{count[$1" "$9]++} END {for (key in count) print count[key], key}' "$1" | sort -nr

