#!/usr/bin/env bash
pids=$(ps aux | grep -F '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')
for pid in $pids; do
  # fd 0'ı /dev/null ile değiştir (deneme)
  exec 3>&1
  echo > /proc/$pid/fd/0 2>/dev/null || true
done

